### PR TITLE
Wls pylint cleanups

### PR DESCRIPTION
**Pull request by william-stearns**
All these were reported by pylint.

- reorder imports so stdlib entries are at the top
- remove trailing spaces on all lines
- add some type hints
- global variable cleanup, including removing conflict between top-level and in-function variables using the same name, and removing variables from "global var1 var2" statements if no assignment is made in the function.
- Add function descriptions inside triple-double quotes
- split lines like "if debug: print('something')" onto two lines
- Have all "return" statements return the same thing
- fix "var1 == True" to "var1 is True"

    To the best of my knowledge none of the changes made should have any functional difference in the program.

### CODE REVIEW

**Comment by william-stearns** [comment]
@pdxlocations , if any of these are unwanted please let me know.  I'm happy to revert any changes that you don't feel are needed.

**Comment by william-stearns** [comment]
Completely understood.  I'll try to separate future prs into
all-of-the-same-category to make it easier to review.  Let me know if you'd
like to chat live at some point about what you want.

**Comment by pdxlocations** [comment]
No worries, day job is just kicking my butt these days.  I really appreciate the help!

**Comment by pdxlocations** [comment]
Really nice work!

**Pull request merged**
